carrinho/urls.py
# carrinho/urls.py

from django.urls import path
from .views import adicionar_ao_carrinho, carrinho_detalhe, checkout, completar_compra,limpar_carrinho, historico_compras
from carrinho import views

app_name = 'carrinho'

urlpatterns = [
    path('adicionar/<int:produto_id>/', adicionar_ao_carrinho, name='adicionar'),
    path('', carrinho_detalhe, name='carrinho_detalhe'),
    path('checkout/', checkout, name='checkout'),
    path('completar_compra/', completar_compra, name='completar_compra'),
    path('limpar/', limpar_carrinho, name='limpar'),
    path('historico/', historico_compras, name='historico_compras'),

]

conecta/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from produtos.admin import custom_admin_site

urlpatterns = [
    path('admin/', admin.site.urls),
    path('custom_admin/', custom_admin_site.urls),
    path('', include('core.urls')),
    path('produtos/', include('produtos.urls')),
    path('carrinho/', include('carrinho.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import IndexView, ContatoView, LoginView, RegistrarView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('index/',IndexView.as_view(), name='Index'),
    path('contato/', ContatoView.as_view(), name='contato'),
    path('login/', LoginView.as_view(), name='login'),
    path('registrar/', RegistrarView.as_view(), name= 'registrar'),
   
]

produtos/urls.py
from django.urls import path
from .views import ProdutosListView, ProdutosCreateView, ProdutosUpdateView, ProdutoDetailView, GrupoDetailView, GrupoListView,GrupoProdutosView, filtrar_produtos
from produtos import views

urlpatterns = [
    path('', ProdutosListView.as_view(), name='produtos_list'),  # URL para listar produtos
    path('produto/novo/', ProdutosCreateView.as_view(), name='produtos_create'),  # URL para criar um novo produto
    path('produto/<int:pk>/editar/', ProdutosUpdateView.as_view(), name='produtos_update'),  # URL para editar um produto
    path('produto/<int:pk>/', ProdutoDetailView.as_view(), name='produto_detalhe'),  # URL para detalhes de um produto
    path('grupo/<int:pk>/', GrupoDetailView.as_view(), name='grupo_detalhe'),  # URL para detalhes de um grupo
   
    path('', GrupoListView.as_view(), name='grupo_list'),
    path('grupo/<int:grupo_id>/', GrupoProdutosView.as_view(), name='grupo_produtos'),
    path('filtrar_produtos/', filtrar_produtos, name='filtrar_produtos'),


]

produtos/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.db.models.signals import pre_save
from stdimage import StdImageField
from django.utils.html import mark_safe

# Modelo base para adicionar campos comuns a todos os modelos que o herdam
class Base(models.Model):
    criado = models.DateField('Data de Criação', auto_now_add=True)  # Data de criação automática
    modificado = models.DateTimeField('Data de Modificação', auto_now=True)  # Data de modificação automática
    ativo = models.BooleanField('Ativo?', default=True)  # Indicador de ativo/inativo

    class Meta:
        abstract = True  # Define o modelo como abstrato (não cria tabela no banco de dados)

# Modelo para Família de Produtos
class Familia(models.Model):
    nome = models.CharField('Nome', max_length=50)  # Nome da família

    def __str__(self):
        return self.nome  # Representação em string do modelo

    class Meta:
        verbose_name = 'Família'  # Nome singular no admin
        verbose_name_plural = 'Famílias'  # Nome plural no admin

# Modelo para Coleção de Produtos
class Colecao(models.Model):
    nome = models.CharField('Nome', max_length=50)  # Nome da coleção

    def __str__(self):
        return self.nome  # Representação em string do modelo

    class Meta:
        verbose_name = 'Coleção'  # Nome singular no admin
        verbose_name_plural = 'Coleções'  # Nome plural no admin

# Modelo para Grupo de Produtos
class Grupo(models.Model):
    nome = models.CharField('Nome', max_length=50)  # Nome do grupo
    imagem = StdImageField('Imagem', upload_to='produtos', variations={'thumbnail': (90, 90)}, blank=True, null=True)
    descricao = models.TextField('Descrição', max_length=100,blank=True, null=True)

    def __str__(self):
        return self.nome  # Representação em string do modelo
    
    def imagem_tag(self):
        try:
            return mark_safe(f'<img src="{self.imagem.url}" width="80" height="80" />')
        except AttributeError:
            return "No Image"

    imagem_tag.short_description = 'Imagem'

    def save(self, *args, **kwargs):
        if not self.imagem:
            self.imagem = DEFAULT_IMAGE_PATH  # Define a imagem padrão
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Grupo'  # Nome singular no admin
        verbose_name_plural = 'Grupos'  # Nome plural no admin

# Modelo para Origem de Produtos
class Origem(models.Model):
    nome = models.CharField('Nome', max_length=50)  # Nome da origem

    def __str__(self):
        return self.nome  # Representação em string do modelo

    class Meta:
        verbose_name = 'Origem'  # Nome singular no admin
        verbose_name_plural = 'Origens'  # Nome plural no admin

# Modelo para Localidade de Produtos
class Localidade(models.Model):
    nome = models.CharField('Nome', max_length=50)  # Nome da localidade

    def __str__(self):
        return self.nome  # Representação em string do modelo

    class Meta:
        verbose_name = 'Localidade'  # Nome singular no admin
        verbose_name_plural = 'Localidades'  # Nome plural no admin

# Modelo para Produtos, herdando de Base
# Caminho para a imagem padrão
DEFAULT_IMAGE_PATH = 'path/to/default/image.jpg'

class Produtos(Base):
    nome = models.CharField('Nome', max_length=50)
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE, blank=True, null=True)
    descricao = models.CharField('Descrição', max_length=100, blank=True, null=True)
    familia = models.ForeignKey(Familia, on_delete=models.CASCADE, blank=True, null=True)
    colecao = models.ForeignKey(Colecao, on_delete=models.CASCADE, blank=True, null=True, default=None)
    imagem = StdImageField('Imagem', upload_to='produtos', variations={'thumbnail': (90, 90)}, blank=False, null=False)
    tamanho = models.CharField('Tamanho', max_length=10, blank=True, null=True)
    peso = models.DecimalField('Peso (em gramas)', max_digits=6, decimal_places=2, blank=False, null=False)
    quantidade = models.IntegerField('Quantidade', default=1)

    def __str__(self):
        return self.nome

    def imagem_tag(self):
        try:
            return mark_safe(f'<img src="{self.imagem.url}" width="80" height="80" />')
        except AttributeError:
            return "No Image"

    imagem_tag.short_description = 'Imagem'

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    def save(self, *args, **kwargs):
        if not self.imagem:
            self.imagem = DEFAULT_IMAGE_PATH  # Define a imagem padrão
        super().save(*args, **kwargs)

produtos/forms.py
from django import forms
from .models import Produtos, Grupo, Colecao, Familia

# Formulário para o modelo de Produtos
class ProdutosModelForm(forms.ModelForm):
    class Meta:
        model = Produtos  # Define o modelo a ser utilizado pelo formulário
        fields = ['nome', 'descricao', 'grupo', 'familia', 'colecao', 'imagem', 'tamanho', 'peso', 'ativo']  # Campos incluídos no formulário

# Formulário para filtrar produtos
class ProdutoFilterForm(forms.Form):
    grupo = forms.ModelChoiceField(queryset=Produtos.objects.values_list('grupo', flat=True).distinct(), required=False)
    familia = forms.ModelChoiceField(queryset=Produtos.objects.values_list('familia', flat=True).distinct(), required=False)
    colecao = forms.ModelChoiceField(queryset=Produtos.objects.values_list('colecao', flat=True).distinct(), required=False)
    ativo = forms.BooleanField(required=False, label='Ativo')

# Formulário personalizado para administração de Produtos
class ProdutosAdminForm(forms.ModelForm):
    class Meta:
        model = Produtos
        exclude = ['slug']  # Exclui o campo 'slug' do formulário

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['slug'].widget.attrs['readonly'] = True  # Define o campo 'slug' como somente leitura

produtos/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.urls import reverse_lazy
from .models import Colecao, Produtos, Grupo
from .forms import ProdutosModelForm, ProdutoFilterForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.template.loader import get_template


class ProdutosListView(ListView):
    model = Produtos
    template_name = 'produtos/produtos_list.html'
    context_object_name = 'produtos'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ProdutoFilterForm(self.request.GET)
        context['grupos'] = Grupo.objects.all()

        grupo_id = self.request.GET.get('grupo')
        if grupo_id:
            context['grupo_selecionado'] = get_object_or_404(Grupo, pk=grupo_id)
        else:
            context['grupo_selecionado'] = None

        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = ProdutoFilterForm(self.request.GET)
        if form.is_valid():
            if form.cleaned_data.get('colecao'):
                queryset = queryset.filter(colecao=form.cleaned_data['colecao'])
            if form.cleaned_data.get('familia'):
                queryset = queryset.filter(familia=form.cleaned_data['familia'])
            if form.cleaned_data.get('ativo') is not None:
                queryset = queryset.filter(ativo=form.cleaned_data['ativo'])
            if form.cleaned_data.get('grupo'):
                queryset = queryset.filter(grupo=form.cleaned_data['grupo'])
        return queryset

class ProdutosCreateView(CreateView):
    model = Produtos
    form_class = ProdutosModelForm
    template_name = 'produtos/produtos_create.html'
    success_url = reverse_lazy('produtos_list')

class ProdutosUpdateView(UpdateView):
    model = Produtos
    form_class = ProdutosModelForm
    template_name = 'produtos/produtos_create.html'
    success_url = reverse_lazy('produtos_list')

class ProdutoDetailView(DetailView):
    model = Produtos
    template_name = 'produtos/produto_detalhe.html'
    context_object_name = 'produto'

class GrupoDetailView(DetailView):
    model = Grupo
    template_name = 'produtos/grupo_detalhe.html'
    context_object_name = 'grupo'

def produtos_create(request):
    if request.method == 'POST':
        form = ProdutosModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('produtos_list')
    else:
        form = ProdutosModelForm()
    return render(request, 'produtos/produtos_create.html', {'form': form})

def produtos_list(request):
    grupo_id = request.GET.get('grupo')
    if grupo_id:
        grupo_selecionado = get_object_or_404(Grupo, id=grupo_id)
        produtos = Produtos.objects.filter(grupo=grupo_selecionado)
    else:
        produtos = Produtos.objects.all()
        grupo_selecionado = None

    grupos = Grupo.objects.all()
    return render(request, 'produtos/produtos_list.html', {
        'produtos': produtos,
        'grupos': grupos,
        'grupo_selecionado': grupo_selecionado,
        'form': ProdutoFilterForm(request.GET),
    })

class GrupoListView(ListView):
    model = Grupo
    template_name = 'produtos/grupo_list.html'
    context_object_name = 'grupos'

class GrupoProdutosView(ListView):
    model = Produtos
    template_name = 'produtos/grupo_produtos.html'
    context_object_name = 'produtos'

    def get_queryset(self):
        grupo_id = self.kwargs.get('grupo_id')
        return Produtos.objects.filter(grupo_id=grupo_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        grupo_id = self.kwargs.get('grupo_id')
        context['grupo'] = get_object_or_404(Grupo, pk=grupo_id)
        return context
    
def filtrar_produtos(request):
    grupo = request.GET.get('grupo')
    familia = request.GET.get('familia')
    colecao = request.GET.get('colecao')
    ativo = request.GET.get('ativo')

    produtos = Produtos.objects.all()

    if grupo:
        produtos = produtos.filter(grupo=grupo)
    if familia:
        produtos = produtos.filter(familia=familia)
    if colecao:
        produtos = produtos.filter(colecao=colecao)
    if ativo:
        produtos = produtos.filter(ativo=(ativo == 'true'))

    for produto in produtos:
        if not produto.imagem:
            produto.imagem_url = 'Sem Imagem' 
        else:
            produto.imagem_url = produto.imagem.url

    context = {
        'produtos': produtos,
    }

    return render(request, 'produtos/produtos_lista_parcial.html', context)

def colecao(request):
    colecoes = Colecao.objects.all() 
    return render(request, 'produtos/produtos_list.html', {'colecoes': colecoes})

produtos/templates/produtos/grupo_detalhe.html
<!-- Detalhe dos produtos por Grupo -->

{% extends 'base.html' %}

{% block content %}
<style>
    .bi-plus {
        color: coral;
        font-size: 2.5rem;
    }
    .bi-plus:hover {
        opacity: 0.8;
        color: rgb(152, 152, 152);
    }
</style>
<div class="container mt-5">
    <h1 class="text-center">
        Demonstrativo de Produtos de: {{ grupo.nome }}
        <a href="{% url 'produtos_list' %}" title="Voltar Para Outras Coleções">
            <i class="bi bi-plus fs-4"></i>
        </a>
    </h1>

    <div class="row">
        {% for produto in grupo.produtos_set.all %}
        <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
            <div class="card h-100">
                {% if produto.imagem and produto.imagem.url %}
                <img src="{{ produto.imagem.url }}" class="card-img-top" alt="{{ produto.nome }}">
                {% else %}
                <img src="/path/to/default/image.jpg" class="card-img-top" alt="Sem Imagem">
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'produto_detalhe' produto.pk %}" class="text-decoration-none">{{ produto.nome }}</a>
                    </h5>
                    <p class="card-text">Descrição: {{ produto.descricao }}</p>
                    <p class="card-text">Família: {{ produto.familia }}</p>
                    <p class="card-text">Peso: {{ produto.peso }} gr.</p>
                    <p class="card-text"><strong>Grupo:</strong> {{ produto.grupo }}</p>
                    
                    <form action="{% url 'carrinho:adicionar' produto.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="quantidade">Quantidade</label>
                            <input type="number" name="quantidade" class="form-control" id="quantidade" value="1" min="1">
                        </div>
                        <button type="submit" class="btn btn-custom">Adicionar ao Carrinho</button>
                    </form>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-12">
            <p class="text-center">Nenhum produto encontrado neste grupo.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

produtos/templates/produtos/grupo_produtos.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <h1 class="text-center">Produtos do Grupo: {{ grupo.nome }}</h1>
    <div class="row">
        {% for produto in produtos %}
        <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
            <div class="card h-100">
                {% if produto.imagem and produto.imagem.url %}
                <img src="{{ produto.imagem.url }}" class="card-img-top" alt="{{ produto.nome }}">
                {% else %}
                <img src="/path/to/default/image.jpg" class="card-img-top" alt="Sem Imagem">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'produto_detalhe' produto.pk %}" class="text-decoration-none">{{ produto.nome }}</a>
                    </h5>
                    <p class="card-text">{{ produto.descricao }}</p>
                    <p class="card-text">Família: {{ produto.familia }}</p>
                    <p class="card-text">Peso: {{ produto.peso }} gr.</p>
                    <p class="card-text"><strong>Grupo:</strong> {{ produto.grupo }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

produtos/templates/produtos/header.html
<!-- templates/seu_app/partials/header.html -->


<header>
    <center><h1></h1></center>
       
</header>

produtos/templates/produtos/produto_detalhe.html
{% extends 'base.html' %}

{% block content %}
<title>Detalhes do Produto</title>
<style>
    h1 {
        font-family: 'Playfair Display', serif;
        font-size: 28px;
        margin-bottom: 20px;
        text-align: center;
        color: #333;
    }

    .card {
        border: 2px solid #ddd;
        border-radius: 15px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        background-color: #f9f9f9;
        color: #333;
        padding: 20px;
        transition: transform 0.6s ease, box-shadow 0.8s ease;
        margin: 20px;
    }

    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15);
    }

    .card-img-top {
        width: 40%;
        height: auto;
        transition: transform 0.5s ease;
        border-radius: 10px;
    }

    .card:hover .card-img-top {
        transform: scale(2.1);
    }

    .card-body {
        padding: 2px;
        text-align: center;
        margin-bottom: 10px;
    }

    .card-body p {
        font-family: 'Cormorant Garamond', serif;
        font-size: 18px;
        color: #555;
        margin-bottom: 10px;
        text-align: left;
    }

    .container {
        max-width: 1500px;
        margin: 0 auto;
        padding: 2px;
    }

    .card-container {
        display: flex;
        flex-wrap: wrap;
        gap: 20px;
    }

    .card-container .card {
        flex: 1;
        min-width: 45%;
    }

    @media (max-width: 768px) {
        .card-container .card {
            min-width: 100%;
        }
    }

    .btn-custom {
        background-color: #d4af37;
        border: none;
        color: white;
        padding: 10px 20px;
        font-size: 16px;
        border-radius: 5px;
        transition: background-color 0.3s ease;
    }

    .btn-custom:hover {
        background-color: #c39e27;
    }

    .form-control {
        border: 1px solid #ccc;
        border-radius: 4px;
        padding: 8px;
    }
</style>

<div class="container">
    <h1>{{ produto.nome }}</h1>

    <div class="card-container">
        <div class="card">
            <div class="card-body">
                <img src="{{ produto.imagem.url }}" alt="{{ produto.nome }} Imagem" class="img-fluid card-img-top">
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <p><strong>DESCRIÇÃO:</strong> {{ produto.descricao }}</p>
                <p><strong>FAMÍLIA:</strong> {{ produto.familia }}</p>
                <p><strong>COLEÇÃO:</strong> {{ produto.colecao }}</p>
                <p><strong>PESO:</strong> {{ produto.peso }} gramas</p>
                <p><strong>TAMANHO:</strong> {{ produto.tamanho }}</p>
                <form action="{% url 'carrinho:adicionar' produto.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="quantidade">Quantidade</label>
                        <input type="number" name="quantidade" class="form-control" id="quantidade" value="1" min="1">
                    </div>
                    <button type="submit" class="btn btn-custom">Adicionar ao Carrinho</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

produtos/templates/produtos/produtos_create.html
<!-- produtos_create.html -->

{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
      {% for grupo in grupos %}
          <div class="col-6 col-sm-4 col-md-3 col-lg-2 mb-3">
              <div class="text-center">
                  <a href="{% url 'grupo_produtos' grupo.id %}" class="text-decoration-none">
                      <h6 class="card-title">{{ grupo.nome }}</h6>
                  </a>
              </div>
          </div>
      {% endfor %}
  </div>
</div>
  <h1>Novo Produto</h1>
  
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
  </form>
{% endblock %}

produtos/templates/produtos/produtos_list.html
<!-- Lista Geral por Coleção/Grupo -->
{% extends 'base.html' %}
{% block content %}
<style>
    .btn-custom {
        background-color: #faa8a8; 
        color: #ffffff;
        border: none;
        font-family: 'Times New Roman', Times, serif;
        transition: background-color 0.3s, transform 0.3s;
    }

    .btn-custom:hover {
        background-color: #f87a7a;
        transform: scale(1.05);
    }
    
    .card {
        border: none;
        border-radius: 8px;
        overflow: hidden;
        transition: box-shadow 0.3s;
        margin: 80px;
        gap:50px;
    }
    .card-container{
        gap: 20px;
    }
    
    .card:hover {
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }

    .card-img-top {
        height: 200px;
        object-fit: cover;
    }
    
    .card-body {
        text-align: center;
        padding: 1rem;
    }

    h1 {
        font-size: 2rem;
        font-weight: bold;
        
    }

    .card-title {
        font-size: 1.25rem;
        font-weight: 500;
    }

    .card-text {
        font-size: 1rem;
        color: #555555;
    }

    .form-control {
        border-radius: 4px;
    }

    @media (max-width: 1200px) {
        .card-img-top {
            height: 180px;
        }
    }

    @media (max-width: 992px) {
        .card-img-top {
            height: 160px;
        }
    }

    @media (max-width: 768px) {
        .card-img-top {
            height: 140px;
        }
        
        h1 {
            font-size: 1.5rem;
        }
    }

    @media (max-width: 576px) {
        .card-img-top {
            height: 80px;
        }
        
        .card-body {
            padding: 0.5rem;
        }

        .card-title {
            font-size: 1rem;
        }

        .card-text {
            font-size: 0.875rem;
        }
    }
</style>

<div class="container-fluid col-md-9">
    <h1 class="text-center">Conheça as nossas Coleções</h1>

    <div class="row">
        {% for grupo in grupos %}
        <div class="col-lg-4 col-md-6 col-sm-12- mb-2">
            <div class="card h-100 text-center p-4 mb-2">
                {% if grupo.imagem and grupo.imagem.url %}
                <img src="{{ grupo.imagem.url }}" class="card-img-top" alt="{{ grupo.nome }}">
                {% else %}
                <img src="/path/to/default/image.jpg" class="card-img-top" alt="Sem Imagem">
                {% endif %}
                <div class="card-body">
                    <a href="{% url 'grupo_produtos' grupo.id %}" class="text-decoration-none">
                        <h6 class="card-title">{{ grupo.nome }}</h6>
                        <p>{{ grupo.descricao}}</p>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<br>
<br>
<br>
{% endblock %}

produtos/templates/produtos/produtos_lista_parcial.html
<!-- produtos_lista_parcial.html -->
{% load bootstrap4 static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Catálogo Geral</title>
    {% bootstrap_css %}
    <style>
        body {
            background: linear-gradient(white, rgb(254, 213, 220));
        }
        h1 {
            font-family: 'Times New Roman', Times, serif;
            font-size: 35px;
            font-weight: bold;
            text-align: center;
        }
        .btn-custom {
            background-color: #faa8a8;
            color: #ffffff;
            border: none;
        }
        .card {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
            text-align: center;
            padding: 10px;
            margin: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        .card img {
            max-width: 100%;
            height: auto;
        }
        .card-title {
            font-size: 1.25rem;
            font-weight: bold;
        }
        .card-body {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            flex-grow: 1;
            text-align: left;
            padding: 10px;
        }
        .card-text {
            margin-bottom: 0.5rem;
        }
        .quantity-container {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }
        .quantity-container label {
            margin-right: 10px;
        }
            
            </style>
        </head>
        <body>
    <h1>Catálogo Geral</h1>
    <div class="row">
        {% for produto in produtos %}
            {% if forloop.counter0|divisibleby:4 %}
                </div><div class="row">
            {% endif %}
            <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                <div class="card h-100">
                    {% if produto.imagem %}
                        <img src="{{ produto.imagem.url }}" class="card-img-top" alt="{{ produto.nome }}">
                    {% else %}
                        <img src="Sem Imagem" class="card-img-top" alt="Sem imagem">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="">{{ produto.nome }}</a>
                        </h5>
                        <p class="card-text">Descrição: {{ produto.descricao }}</p>
                        <p class="card-text">Família: {{ produto.familia }}</p>
                        <p class="card-text">Peso: {{ produto.peso }} gr.</p>
                        <p class="card-text">Tamanho: {{ produto.tamanho }}</p>
                        <p class="card-text">Coleção: {{ produto.colecao }}</p>
                        <p class="card-text"><strong>Grupo:</strong> {{ produto.grupo }}</p>
                        <form action="{% url 'carrinho:adicionar' produto.id %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="quantidade_{{ produto.id }}">Quantidade</label>
                                <input type="number" name="quantidade" class="form-control" id="quantidade_{{ produto.id }}" value="1" min="1">
                            </div>
                            <button type="submit" class="btn btn-custom">Adicionar ao Carrinho</button>
                        </form>
                    </div>
                </div>
            </div>
        {% empty %}
            <p class="text-center">Nenhum produto encontrado.</p>
        {% endfor %}
    </div>
    {% bootstrap_javascript %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js" integrity="sha384-pzjw8f+ua7Kw1TIq5tv8P8fEX55Cbsn+EGl5fJYYc5i0OJm2b4QomniwUYoXK5/8" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgYfZbB7TVbP9Y50fuFdS4g5cfsXn5f5/7TqtrV1pI4WxAx3Jb4" crossorigin="anonymous"></script>
</body>
{% include 'partials/footer.html' %}
</html>

produtos/templates/produtos/produtos_update.html
<!-- produtos_update.html -->

{% extends 'base.html' %}

      {% endfor %}
  </div>
</div>
{% block content %}
  <h1>Editar Produto</h1>
  
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar Alterações</button>
  </form>
{% endblock %}