carrinho/urls.py
# carrinho/urls.py

from django.urls import path
from .views import adicionar_ao_carrinho, carrinho_detalhe, checkout, completar_compra,limpar_carrinho, historico_compras
from carrinho import views

app_name = 'carrinho'

urlpatterns = [
    path('adicionar/<int:produto_id>/', adicionar_ao_carrinho, name='adicionar'),
    path('', carrinho_detalhe, name='carrinho_detalhe'),
    path('checkout/', checkout, name='checkout'),
    path('completar_compra/', completar_compra, name='completar_compra'),
    path('limpar/', limpar_carrinho, name='limpar'),
    path('historico/', historico_compras, name='historico_compras'),

]

conecta/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from produtos.admin import custom_admin_site

urlpatterns = [
    path('admin/', admin.site.urls),
    path('custom_admin/', custom_admin_site.urls),
    path('', include('core.urls')),
    path('produtos/', include('produtos.urls')),
    path('carrinho/', include('carrinho.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import IndexView, ContatoView, LoginView, RegistrarView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('index/',IndexView.as_view(), name='Index'),
    path('contato/', ContatoView.as_view(), name='contato'),
    path('login/', LoginView.as_view(), name='login'),
    path('registrar/', RegistrarView.as_view(), name= 'registrar'),
   
]

carrinho/models.py
from django.db import models
from django.conf import settings
from produtos.models import Produtos
from django.utils import timezone
from representantes.models import Representante
from formasrecebimento.models import FormasRecebimento

class Base(models.Model):
    criado = models.DateField('Data de Criação', default=timezone.now)
    modificado = models.DateTimeField('Data de Modificação', auto_now=True)
    ativo = models.BooleanField('Ativo?', default=True)

    class Meta:
        abstract = True


class Carrinho(Base):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    finalizado = models.BooleanField(default=False)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    representante = models.ForeignKey(Representante, on_delete=models.SET_NULL, null=True, blank=False)
    formasrecebimento = models.ForeignKey(FormasRecebimento, on_delete=models.SET_NULL, null=True, blank=False) 

    # Colunas herdadas
    representante_nome = models.CharField(max_length=255, null=True, blank=True)
    formasrecebimento_descricao = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'Carrinho de {self.usuario.email} - {"Finalizado" if self.finalizado else "Aberto"}'

    def get_peso_total(self):
        peso_total = 0
        for item in self.itens.all():
            peso_total += item.produto.peso * item.quantidade
        return peso_total
    

    def definir_formasrecebimento(self, formarecebimento):
        self.formasrecebimento = formarecebimento
        self.save()

    
    def save(self, *args, **kwargs):
        if self.representante:
            self.representante_nome = self.representante.nome
        if self.formasrecebimento:
            self.formasrecebimento_descricao = self.formasrecebimento.descricao
        super().save(*args, **kwargs)

    def finalizar(self):
        self.finalizado = True
        self.save()
        return self
    

class ItemCarrinho(Base):
    carrinho = models.ForeignKey(Carrinho, related_name='itens', on_delete=models.CASCADE)
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.quantidade} x {self.produto.nome}'

    @property
    def peso_total(self):
        return self.produto.peso * self.quantidade

class Compra(Base):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    data_compra = models.DateTimeField(auto_now_add=True)
    peso_total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    representante = models.ForeignKey(Representante, on_delete=models.SET_NULL, null=True, blank=False)
    formasrecebimento = models.ForeignKey(FormasRecebimento, on_delete=models.SET_NULL, null=True, blank=False) 
       # Colunas herdadas
    representante_nome = models.CharField(max_length=255, null=True, blank=True)
    formasrecebimento_descricao = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'Compra de {self.usuario.email} em {self.data_compra}'

    def calcular_peso_total(self):
        peso_total = 0
        for item in self.itens.all():
            peso_total += item.produto.peso * item.quantidade
        self.peso_total = peso_total
        self.save()
        return peso_total
    
    def definir_formasrecebimento(self, formarecebimento):
        self.formasrecebimento = formarecebimento
        self.save()
    
    
    def save(self, *args, **kwargs):
        if self.representante:
            self.representante_nome = self.representante.nome
        if self.formasrecebimento:
            self.formasrecebimento_descricao = self.formasrecebimento.descricao
        super().save(*args, **kwargs)

class ItemCompra(Base):
    compra = models.ForeignKey(Compra, related_name='itens', on_delete=models.CASCADE)
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    formasrecebimento = models.ForeignKey(FormasRecebimento, on_delete=models.SET_NULL, null=True, blank=False) 
    formasrecebimento_descricao = models.TextField(null=True, blank=True)
     # Colunas herdadas
    representante = models.ForeignKey(Representante, on_delete=models.SET_NULL, null=True, blank=False)
    representante_nome = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f'{self.quantidade} x {self.produto.nome}'

    @property
    def peso_total(self):
        return self.produto.peso * self.quantidade

    def definir_formasrecebimento(self, formarecebimento):
        self.formasrecebimento = formarecebimento
        self.save()
    

    def save(self, *args, **kwargs):
        if self.representante:
            self.representante_nome = self.representante.nome
        if self.formasrecebimento:
            self.formasrecebimento_descricao = self.formasrecebimento.descricao
        super().save(*args, **kwargs)

carrinho/views.py
# carrinho/views.py
import logging
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Carrinho, ItemCarrinho, Compra, ItemCompra
from produtos.models import Produtos
from decimal import Decimal
from django.contrib import messages
from django.core.mail import send_mail
import requests
from decimal import Decimal, ROUND_HALF_UP
from representantes.models import Representante
from formasrecebimento.models import FormasRecebimento
from django.core.paginator import Paginator

logger = logging.getLogger(__name__)

@login_required
def adicionar_ao_carrinho(request, produto_id):
    produto = get_object_or_404(Produtos, id=produto_id)
    quantidade = int(request.POST.get('quantidade', 1))
    
    carrinho, created = Carrinho.objects.get_or_create(usuario=request.user, finalizado=False)
    item, item_created = ItemCarrinho.objects.get_or_create(carrinho=carrinho, produto=produto)
    
    if item_created:
        item.quantidade = quantidade
    else:
        item.quantidade += quantidade
    
    item.save()

    # Adiciona uma mensagem de sucesso
    messages.success(request, "Item adicionado ao carrinho com sucesso.")
    
    return redirect('produtos_list')

@login_required
def carrinho_detalhe(request):
    api_key = "goldapi-141hslyhvp7qw-io"
    symbol = "XAU"
    curr = "USD"    
    url = f"https://www.goldapi.io/api/{symbol}/{curr}"    
    headers = {"x-access-token": api_key,"Content-Type": "application/json"}

    def make_gapi_request():
        try:
            response = requests.get(url, headers=headers)
            response.raise_for_status()  # Lança HTTPError para respostas ruins
            data = response.json()
            return Decimal(data['price'])
        except requests.exceptions.RequestException as e:
            # Tratar exceções de requisição como erros de conexão ou timeout
            print(f"Erro ao buscar preço do ouro: {e}")
            return None
        except (KeyError, ValueError) as e:
            # Tratar erros de parsing JSON ou chave 'price' ausente
            print(f"Erro ao analisar dados de preço do ouro: {e}")
            return None

    # Chamada à função para obter o preço do ouro
    gold_price_per_gram = make_gapi_request()

    if gold_price_per_gram is not None:
        # Limitar as casas decimais a 3
        gold_price_per_gram = gold_price_per_gram.quantize(Decimal('0.001'), rounding=ROUND_HALF_UP)

    # Obter o carrinho do usuário e calcular totais
    carrinho = Carrinho.objects.filter(usuario=request.user, finalizado=False).first()
    total_quantidade = Decimal('0')
    total_peso = Decimal('0')
    produtos_comprados = []
    representantes = Representante.objects.all()
    formasrecebimento = FormasRecebimento.objects.all()

    if carrinho:
        for item in carrinho.itens.all():
            quantidade = item.quantidade
            peso = item.produto.peso

            total_quantidade += Decimal(quantidade)
            total_peso += Decimal(peso) * Decimal(quantidade)
            produtos_comprados.append({
                'nome': item.produto.nome,
                'quantidade': quantidade,
                'peso': peso
            })

    # Obter histórico de compras do usuário
    compras = Compra.objects.filter(usuario=request.user).order_by('-data_compra')

    # Preparar contexto para renderizar o template
    context = {
        'carrinho': carrinho,
        'total_quantidade': total_quantidade,
        'total_peso': total_peso,
        'compras': compras,
        'produtos_comprados': produtos_comprados,
        'gold_price_per_gram': gold_price_per_gram,
        'representantes': representantes,
        'formasrecebimento': formasrecebimento,
        
    }

    return render(request, 'carrinho_detalhe.html', context)

@login_required
def checkout(request):
    produtos_no_carrinho = ItemCarrinho.objects.filter(carrinho__usuario=request.user, carrinho__finalizado=False)
    total_peso = sum(item.produto.peso * item.quantidade for item in produtos_no_carrinho)
    representantes = Representante.objects.all()
    formasrecebimento = FormasRecebimento.objects.all()  # Obtendo formas de recebimento
    contexto = {
        'produtos': produtos_no_carrinho,
        'total_peso': total_peso,
        'representantes': representantes,
        'formasrecebimento': formasrecebimento,  # Passando formas de recebimento para o contexto
    }
    return render(request, 'carrinho/checkout.html', contexto)

@login_required
def completar_compra(request):
    if request.method == 'POST':
        try:
            carrinho = get_object_or_404(Carrinho, usuario=request.user, finalizado=False)
        except Carrinho.DoesNotExist:
            return HttpResponse("Carrinho não encontrado ou já finalizado.", status=404)

        total_quantidade = Decimal('0')
        total_peso = Decimal('0')

        for item in carrinho.itens.all():
            total_quantidade += Decimal(item.quantidade)
            total_peso += Decimal(item.produto.peso) * Decimal(item.quantidade)

        representante_id = request.POST.get('representante_id')
        if not representante_id:
            return HttpResponse("Representante não selecionado.", status=400)

        representante = get_object_or_404(Representante, id=representante_id)
        carrinho.representante = representante

        formasrecebimento_id = request.POST.get('formasrecebimento_id')
        if not formasrecebimento_id:
            return HttpResponse("Forma de recebimento não selecionada.", status=400)

        formasrecebimento = get_object_or_404(FormasRecebimento, id=formasrecebimento_id)

        # Cria a compra e salva a forma de recebimento
        compra = Compra.objects.create(
            usuario=request.user,
            peso_total=total_peso,
            representante=representante,
            formasrecebimento=formasrecebimento
        )

        carrinho.finalizado = True
        carrinho.save()

        for item in carrinho.itens.all():
            ItemCompra.objects.create(
                compra=compra,
                produto=item.produto,
                quantidade=item.quantidade
            )

        nome = request.POST.get('nome', 'N/A')  # Valor padrão caso o nome não seja fornecido
        email = request.POST.get('email', 'N/A')  # Valor padrão caso o e-mail não seja fornecido

        produtos_comprados = "\n".join([
            f"{item.produto.nome} - {item.quantidade} unidades, {item.produto.peso} gramas cada"
            for item in carrinho.itens.all()
        ])

        email_destinatarios = ['leo.kaique.010@gmail.com', 'antonio@joalheriasgravina.com.br']
        if email and email != 'N/A':
            email_destinatarios.append(email)

        assunto = 'Detalhes do Pedido'
        mensagem = (f"Nome: {nome}\n"
                    f"Email: {email}\n\n"
                    f"Total de Itens: {total_quantidade}\n"
                    f"Peso Total: {total_peso} gr\n\n"
                    f"Produtos Comprados:\n{produtos_comprados}\n"
                    f"Forma de Recebimento: {formasrecebimento.descricao}")

        try:
            send_mail(assunto, mensagem, settings.EMAIL_HOST_USER, email_destinatarios)
        except Exception as e:
            return HttpResponse(f'Erro ao enviar e-mail: {e}', status=500)

        return render(request, 'carrinho/compra_concluida.html', {
            'total_quantidade': total_quantidade,
            'total_peso': total_peso,
            'produtos_comprados': carrinho.itens.all()
        })

    return render(request, 'carrinho/compra_concluida.html')

@login_required
def limpar_carrinho(request):
    carrinho = get_object_or_404(Carrinho, usuario=request.user, finalizado=False)
    carrinho.itens.all().delete()
    return redirect("carrinho:carrinho_detalhe")

@login_required
def historico_compras(request):
    historico = Compra.objects.filter(usuario=request.user).prefetch_related('itens__produto').order_by('id')
    paginator = Paginator(historico, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    compras_com_forma = []
    
    for compra in historico:
        compras_com_forma.append({
            'id': compra.id,
            'criado_em': compra.data_compra,
            'peso_total': compra.calcular_peso_total(),
            'representante': compra.representante,
            'formasrecebimento': compra.formasrecebimento,
            'itens': compra.itens.all()
        })
    
    return render(request, 'historico_compras.html', {'historico': compras_com_forma,'page_obj': page_obj})

carrinho/templates/carrinho_detalhe.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
<head>
    <title>Meu Carrinho</title>
    {% bootstrap_css %}
    <style>
        body {
            background: linear-gradient(white, rgb(255, 208, 208));
            font-family: 'Times New Roman', Times, serif;
            padding-bottom: 35%;
        }
        
        .card-custom {
            background-color: #f5e7e7;
            color: rgb(255, 162, 12);
            text-decoration-line: underline;
            border-color: aliceblue;
            font-size: medium;
            box-shadow: inset;
        }

        h1 {
            color: rgb(255, 162, 12);
            text-align: center;
            text-decoration-line: underline;
        }

        table {
            text-align: center;
        }

        th, td {
            color: rgb(2, 37, 46);
            text-align: center;
            vertical-align: middle;
        }
        .btn-custom {
            background-color: #5a88a5;
            color: white;
        }

        .btn-custom1 {
            background-color: #e4a991;
            color: white;
        }
        
        .btn-custom2 {
            background-color: #dd9378;
            color: white;
        }
        
        .btn-custom3 {
            background-color: #557455;
            color: white;
        }

        .btn {
            border-radius: 5px;
            margin: 0 5px;
        }

        .container {
            padding: 20px;
        }
    </style>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><i class="/media/logo.png"> <img src="/media/logo.png" alt="Logo" width="70" height="70" class="d-inline-block align-top"></i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Index' %}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">Meu Carrinho <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        <h1 class="mb-4">Detalhes Carrinho</h1>
        <div class="card mb-4 card-custom">
            <div class="card-body">
                <h5 class="card-title">Cotação do Ouro:</h5>
                {% if gold_price_per_gram %}
                    <p>Preço do ouro por grama: {{ gold_price_per_gram }}</p>
                {% else %}
                    <p>Preço do ouro não disponível no momento.</p>
                {% endif %}
            </div>
        </div>

        {% if carrinho and carrinho.itens.exists %}
        <form method="POST" action="{% url 'carrinho:completar_compra' %}">
            {% csrf_token %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Produto</th>
                        <th>Quantidade</th>
                        <th>Peso</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in carrinho.itens.all %}
                        <tr>
                            <td>{{ item.produto.nome }}</td>
                            <td>{{ item.quantidade }}</td>
                            <td>{{ item.produto.peso }} gr.</td>
                        </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th>Total</th>
                        <th>{{ total_quantidade }}</th>
                        <th>{{ total_peso }} gr.</th>
                    </tr>
                </tfoot>
            </table>
        
            <div class="form-group">
                <label for="formasrecebimento_id">Selecione a Forma de Pagamento:</label>
                <select id="formasrecebimento_id" name="formasrecebimento_id" class="form-control" required>
                    {% for formasrecebimento in formasrecebimento %}
                        <option value="{{ formasrecebimento.id }}">{{ formasrecebimento.descricao }}</option>
                    {% endfor %}
                </select>
            </div>
        
            <div class="form-group">
                <label for="representante_id">Selecione seu Representante:</label>
                <select id="representante_id" name="representante_id" class="form-control" required>
                    {% for representante in representantes %}
                        <option value="{{ representante.id }}">{{ representante.nome }} - {{ representante.regiao }}</option>
                    {% endfor %}
                </select>
            </div>
        
            <div class="mt-3">
                <a href="{% url 'carrinho:limpar' %}" class="btn btn-custom">Limpar Carrinho</a>
                <a href="{% url 'produtos_list' %}" class="btn btn-custom1">Continuar Comprando</a>
                <button type="button" onclick="window.print()" class="btn btn-custom2">Imprimir</button>
                <button type="submit" class="btn btn-custom3">Finalizar Compra</button>
            </div>
        </form>
        {% else %}
            <div class="alert alert-info" role="alert"> 
                Seu carrinho está vazio.
            </div>
        {% endif %}
    </div>

    {% bootstrap_javascript %}
</body>
</html>

carrinho/templates/produtos_list.html
{% load bootstrap4 static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>CATALOGO DE PRODUTOS</title>
    {% bootstrap_css %}
    <style>
body {
    background: linear-gradient(#09314e, #ffff);
    font-family: 'Arial', sans-serif; /* Adicione uma fonte padrão */
}

.card {
    border-radius: 25px;
    overflow: hidden;
    transform: scale(0.78); /* Ajuste o tamanho inicial */
    transition: transform 0.3s ease, box-shadow 0.3s ease;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Adicione uma sombra sutil */
    margin-bottom: 20px; /* Adicione espaçamento entre os cards */
}

.card:hover {
    transform: scale(1.05); /* Aumenta para 105% do tamanho ao passar o mouse */
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2); /* Sombra mais forte no hover */
}

.card-img-top {
    width: 100%;
    height: auto;
    transition: transform 0.3s ease;
}

.card:hover .card-img-top {
    transform: scale(1.1); /* Aumenta para 110% do tamanho ao passar o mouse */
}

.card-body {
    background-color: #93badb;
    color: rgb(207, 235, 225);
    padding: 20px; /* Aumente o padding para um espaçamento melhor */
    text-align: center; /* Centralize o texto */
}

.card-title {
    font-size: 1.8rem;
    margin-bottom: 10px; /* Espaçamento inferior */
}

.card-text {
    font-size: 1.1rem;
    margin-bottom: 20px; /* Espaçamento inferior */
}

.btn-primary {
    font-size: 1.2rem;
    padding: 10px 20px; /* Ajuste o padding para melhor aparência */
    background-color: #256c9e; /* Altere a cor do botão para combinar com o tema */
    border: none; /* Remova a borda padrão */
    transition: background-color 0.3s ease; /* Adicione transição para cor de fundo */
}

.btn-primary:hover {
    background-color: #1e5477; /* Cor mais escura no hover */
}

    </style>
</head>
<body>
   
    <nav class="navbar navbar-expand-lg navbar-light bg-light"  style= background-color:#11ae8f>
        <a class="navbar-brand" href="#">
          <img src="media/produtos/Iron.png" width="65" height="45" class="d-inline-block align-top" alt="">
          Iron
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownProdutos" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Produtos
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownProdutos">
                        <a class="dropdown-item" href="">Adicionar Produto</a>
                        <a class="dropdown-item" href="#">Categoria 2</a>
                        <div class="dropdown-divider"></div>
                        
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownSobre" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Carrinho
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownSobre">
                        <a class="dropdown-item" href="carrinho/historico">Meu Carrinho</a>
                        <div class="dropdown-divider"></div>

                    </div>
                </li>
                </li>
                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownSobre" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dados Financeiros
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownSobre">
                    <a class="dropdown-item" href="#">Meus dados Financeiros</a>
                    <a class="dropdown-item" href="#">Extrato de Dados Financeiros</a>
                </div>
            </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownContato" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Contato
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownContato">
                        <a class="dropdown-item" href="#">Fale Conosco</a>
                        <a class="dropdown-item" href="#">Suporte</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <nav class="navbar navbar-light" style="background-color: #256c9e;">
        <!-- Navbar content -->
    </nav>
    
    <div class="col-md-3">
        <div class="sidebar">
            <h5 style="color: antiquewhite;">Categorias</h5>
            <ul class="nav flex-column">
                {% for grupo in grupos %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'grupo_detalhe' %}">{{ grupo.nome }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <style> 
        h1{ color: rgb(176, 130, 31);}
    </style>
    <center> <h1>CATALOGO DE PRODUTOS</h1></center>
    <div class="container">
        <div class="row">
            {% for produto in produtos %}
                <div class="col-md-4">
                    <div class="card mb-3">
                        {% if produto.imagem %}
                            <img src="{{ produto.imagem.url }}" class="card-img-top" alt="{{ produto.nome }}">
                        {% else %}
                            <img src="{% static 'images/no-image.png' %}" class="card-img-top" alt="Sem imagem disponível">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ produto.nome }}</h5>
                            <p class="card-text">Coleção: {{ produto.colecao }}</p>
                            <p class="card-text">Tamanho: {{ produto.tamanho }}</p>
                            <p class="card-text">Peso: {{ produto.peso }}</p>
                            <form action="{% url 'carrinho:adicionar' produto.id %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="quantidade">Quantidade</label>
        <input type="number" name="quantidade" class="form-control" id="quantidade" value="1" min="1">
    </div>
    <button type="submit" class="btn btn-primary">Adicionar ao Carrinho</button>
</form>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 and not forloop.last %}
                    </div><div class="row">
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <!-- Include jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js" integrity="sha384-pzjw8f+ua7Kw1TIq5tv8P8fEX55Cbsn+EGl5fJYYc5i0OJm2b4QomniwUYoXK5/8" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgYfZbB7TVbP9Y50fuFdS4g5cfsXn5f5/7TqtrV1pI4WxAx3Jb4" crossorigin="anonymous"></script>
    {% bootstrap_javascript %}
</body>
</html>